:global:
  componentName: Group Sync Operator
  githubUrl: https://github.com/appuio/component-group-sync-operator
  feature_goldenTests: true
  testMatrix:
    key: instance
    entries:
      - defaults
      - empty

.gitignore:
  additionalEntries:
    - jsonnetfile.json

.github/workflows/test.yaml:
  goldenTest_makeTarget: golden-diff -e instance=${{ matrix.instance }}
  makeTarget: test -e instance=${{ matrix.instance }}
