:global:
  componentName: group-sync-operator
  githubUrl: https://github.com/appuio/component-group-sync-operator
  feature_goldenTests: true

docs/antora.yml:
  name: group-sync-operator
  title: Group Sync Operator

.gitignore:
  additionalEntries:
    - jsonnetfile.json
