:global:
  componentName: Group Sync Operator
  githubUrl: https://github.com/appuio/component-group-sync-operator
  feature_goldenTests: true

docs/antora.yml:
  name: group-sync-operator
  title: group-sync-operator
